### ISSUE TITLE
Issue: Improper Project Folder Structure

### ISSUE THREAD

**Issue by ahammednibras8** [Muhaiminkpm/FYJ#1]
The current structure of the repository has the following issues:
	1.	Parent Folder Issue:
	•	The entire Flutter project has been placed inside a folder named fyj_flutter_app. However, this folder appears to serve as both the project name and a directory. This is unnecessary and creates confusion.
	•	Ideally, the root folder of the repository should contain the Flutter project files directly, without an additional wrapper folder named after the project.
	2.	Nested Project Issue:
	•	Within the fyj_flutter_app folder, there seems to be another Flutter project. This creates redundancy and makes it difficult for contributors to understand which project is the primary one or how to run it.

Steps to Reproduce:
	1.	Clone the repository using git clone https://github.com/Muhaiminkpm/FYJ.git.
	2.	Navigate through the folder structure and observe the following:
	•	A parent folder named fyj_flutter_app containing another project inside it.
	•	The structure is unclear and unconventional for a Flutter project.

Expected Behavior:
	•	The repository should have a clear, flat structure:
	•	The Flutter project files (e.g., pubspec.yaml, lib/, android/, ios/, etc.) should exist directly at the root of the repository.
	•	There should be no unnecessary nested projects or folders.

Proposed Solution:
	1.	Reorganize the Repository:
	•	Move the Flutter project files currently inside fyj_flutter_app directly to the root of the repository.
	•	Remove any unnecessary nested projects.
	2.	Clean Up the Folder Structure:
	•	Ensure the repository follows a standard Flutter project folder structure.
	•	Remove redundant folders or nested projects to avoid confusion.

Benefits:
	•	Simplifies navigation and understanding of the project structure.
	•	Makes the repository more accessible to contributors and easier to clone and run.

Priority: High

**Comment by Muhaiminkpm** [comment]
ok I solved it,

**Comment by ahammednibras8** [comment]
Good Job
